export const Characters = [
  {
    id: "bardock",
    name: "Bardock",
    description: "Papá de Goku",
    species: "Saiyan",
  },
  {
    id: "gohan",
    name: "Gohan",
    description: "Hijo mayor de Goku",
    species: "Saiyan",
  },
  {
    id: "goku",
    name: "Goku",
    description: "Protagonista de DB",
    species: "Saiyan",
  },
  {
    id: "krillin",
    name: "Krillin",
    description: "Mejor amigo de Goku",
    species: "Human",
  },
  {
    id: "majin_buu",
    name: "Majin Buu",
    description: "Enemigo en la saga de Buu en DB Z",
    species: "Majin",
  },
  {
    id: "super_buu",
    name: "Super Majin Buu",
    description: "Enemigo en la saga de Buu en DB Z",
    species: "Majin",
  },
  {
    id: "evil_buu",
    name: "Evil Majin Buu",
    description: "Enemigo en la saga de Buu en DB Z",
    species: "Majin",
  },
  {
    id: "kid_buu",
    name: "Kid Majin Buu",
    description: "Enemigo en la saga de Buu en DB Z",
    species: "Majin",
  },
  {
    id: "piccolo",
    name: "Piccolo",
    description: "Enemigo y despues amigo de Goku",
    species: "Namekian",
  },
  {
    id: "vegeta",
    name: "Vegeta",
    description: "Principe de los Saiyajin",
    species: "Saiyan",
  },
  {
    id: "bulma",
    name: "Bulma",
    description: "Esposa de Vegeta",
    species: "Human",
  },
  {
    id: "caulifla",
    name: "Caulifla",
    description: "Saiyajin de otro universo",
    species: "Saiyan",
  },
  {
    id: "gine",
    name: "Gine",
    description: "Mamá de Goku",
    species: "Saiyan",
  },
  {
    id: "milk",
    name: "Milk",
    description: "Esposa de Goku",
    species: "Human",
  },
  {
    id: "no18",
    name: "Androide No. 18",
    description: "Esposa de Krillin",
    species: "Android",
  },
  {
    id: "videl",
    name: "Videl",
    description: "Esposa de Gohan",
    species: "Human",
  },
  {
    id: "goten",
    name: "Goten",
    description: "Hijo menor de Goku",
    species: "Saiyan",
  },
  {
    id: "trunks",
    name: "Trunks",
    description: "Hijo de Vegeta",
    species: "Saiyan",
  },
];
